env:
  browser: true
  commonjs: true
  es2021: true
  jest/globals: true
extends:
  - 'standard'
  - 'plugin:import/errors'
  - 'plugin:import/warnings'
  - 'plugin:jest/recommended'
  - 'plugin:node/recommended'
  - 'plugin:prettier/recommended'
  - 'plugin:promise/recommended'
plugins:
  - 'jest'
  - 'prettier'
parserOptions:
  ecmaVersion: 12
rules:
  prettier/prettier:
    - error
